### ISSUE TITLE
Allow TAs/Tutors/AIs to see a list of students they've helped in past OH

### ISSUE THREAD

**Issue by vivrekar** [Cal-CS-61A-Staff/oh-queue#141] opened 2017-11-17 22:24 UTC
Helpful in case we want to follow-up with a student or clarify a statement we made while helping them, in case OH ends before we can finish, or we say something misleading while helping them.

**Comment by chrononyan** [comment] 2019-02-23 00:12
Can this be merged with #129?

**Comment by vivrekar** [comment] 2019-02-24 08:58
Yes let's do that!

**Comment by ja5087** [comment] 2019-03-06 23:58
Duplicate of #129

**Closed** 2019-03-06 23:59 UTC
Labels: feature-request, unassigned-yet
